version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command: ['start-dev', '--import-realm']
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
      - ./realm-export.json:/opt/keycloak/data/import
