version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ''
      POSTGRES_USER: ''
      POSTGRES_DB: ''

    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: ''
      KEYCLOAK_ADMIN_PASSWORD: ''
      KEYCLOAK_LOGLEVEL: DEBUG
    command: ['start-dev']
    ports:
      - '8080:8080'
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
